import dotenv from 'dotenv';

dotenv.config();

const env = process.env;

export const MONGO_URI = env.MONGO_URI;
export const BREVO_API_KEY = env.BREVO_API_KEY;
export const BREVO_USER = env.BREVO_USER;
export const EMAIL_FROM = env.EMAIL_FROM;
export const ADMIN_API_KEY = env.ADMIN_API_KEY;
export const ADMIN_SEED_EMAIL = env.ADMIN_SEED_EMAIL;
export const ADMIN_SEED_PASSWORD = env.ADMIN_SEED_PASSWORD;
export const NEXT_PUBLIC_APP_URL = env.NEXT_PUBLIC_APP_URL;
export const NEXTAUTH_URL = env.NEXTAUTH_URL;
export const NEXTAUTH_SECRET = env.NEXTAUTH_SECRET;
export const JWT_SECRET = env.JWT_SECRET;
export const FIREBASE_TYPE = env.FIREBASE_TYPE;
export const FIREBASE_PROJECT_ID = env.FIREBASE_PROJECT_ID;
export const FIREBASE_PRIVATE_KEY_ID = env.FIREBASE_PRIVATE_KEY_ID;
export const FIREBASE_PRIVATE_KEY = env.FIREBASE_PRIVATE_KEY;
export const FIREBASE_CLIENT_EMAIL = env.FIREBASE_CLIENT_EMAIL;
export const FIREBASE_CLIENT_ID = env.FIREBASE_CLIENT_ID;
export const FIREBASE_AUTH_URI = env.FIREBASE_AUTH_URI;
export const FIREBASE_TOKEN_URI = env.FIREBASE_TOKEN_URI;
export const FIREBASE_AUTH_PROVIDER_X509_CERT_URL = env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL;
export const FIREBASE_CLIENT_X509_CERT_URL = env.FIREBASE_CLIENT_X509_CERT_URL;
export const FIREBASE_UNIVERSE_DOMAIN = env.FIREBASE_UNIVERSE_DOMAIN;

export default env;
