import dotenv from 'dotenv';
dotenv.config();

export const { 
    MONGO_URI,
    BREVO_API_KEY,
    BREVO_USER,
    ADMIN_API_KEY,
    ADMIN_SEED_EMAIL,
    ADMIN_SEED_PASSWORD,
    NEXT_PUBLIC_APP_URL,
    NEXTAUTH_URL,
    NEXTAUTH_SECRET,
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_UNIVERSE_DOMAIN,
    
} = process.env;